package edm;
// Generated 11-feb-2016 0:18:43 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Animal generated by hbm2java
 */
@Entity
@Table(name="ANIMAL"
    ,catalog="CLARITYCOW"
)
public class Animal  implements java.io.Serializable {


     private int animalId;
     private int sexoId;
     private int razaId;
     private Integer animalMadre;
     private Integer animalCategoriaActual;
     private Integer animalEstadoActual;
     private Integer animalRupActual;
     private Integer animalGrupopesoActual;
     private Float animalPesoActual;
     private Integer animalDiioActual;
     private Integer animalCastrado;

    public Animal() {
    }

	
    public Animal(int animalId, int sexoId, int razaId) {
        this.animalId = animalId;
        this.sexoId = sexoId;
        this.razaId = razaId;
    }
    public Animal(int animalId, int sexoId, int razaId, Integer animalMadre, Integer animalCategoriaActual, Integer animalEstadoActual, Integer animalRupActual, Integer animalGrupopesoActual, Float animalPesoActual, Integer animalDiioActual, Integer animalCastrado) {
       this.animalId = animalId;
       this.sexoId = sexoId;
       this.razaId = razaId;
       this.animalMadre = animalMadre;
       this.animalCategoriaActual = animalCategoriaActual;
       this.animalEstadoActual = animalEstadoActual;
       this.animalRupActual = animalRupActual;
       this.animalGrupopesoActual = animalGrupopesoActual;
       this.animalPesoActual = animalPesoActual;
       this.animalDiioActual = animalDiioActual;
       this.animalCastrado = animalCastrado;
    }
   
     @Id 

    
    @Column(name="ANIMAL_ID", unique=true, nullable=false)
    public int getAnimalId() {
        return this.animalId;
    }
    
    public void setAnimalId(int animalId) {
        this.animalId = animalId;
    }

    
    @Column(name="SEXO_ID", nullable=false)
    public int getSexoId() {
        return this.sexoId;
    }
    
    public void setSexoId(int sexoId) {
        this.sexoId = sexoId;
    }

    
    @Column(name="RAZA_ID", nullable=false)
    public int getRazaId() {
        return this.razaId;
    }
    
    public void setRazaId(int razaId) {
        this.razaId = razaId;
    }

    
    @Column(name="ANIMAL_MADRE")
    public Integer getAnimalMadre() {
        return this.animalMadre;
    }
    
    public void setAnimalMadre(Integer animalMadre) {
        this.animalMadre = animalMadre;
    }

    
    @Column(name="ANIMAL_CATEGORIA_ACTUAL")
    public Integer getAnimalCategoriaActual() {
        return this.animalCategoriaActual;
    }
    
    public void setAnimalCategoriaActual(Integer animalCategoriaActual) {
        this.animalCategoriaActual = animalCategoriaActual;
    }

    
    @Column(name="ANIMAL_ESTADO_ACTUAL")
    public Integer getAnimalEstadoActual() {
        return this.animalEstadoActual;
    }
    
    public void setAnimalEstadoActual(Integer animalEstadoActual) {
        this.animalEstadoActual = animalEstadoActual;
    }

    
    @Column(name="ANIMAL_RUP_ACTUAL")
    public Integer getAnimalRupActual() {
        return this.animalRupActual;
    }
    
    public void setAnimalRupActual(Integer animalRupActual) {
        this.animalRupActual = animalRupActual;
    }

    
    @Column(name="ANIMAL_GRUPOPESO_ACTUAL")
    public Integer getAnimalGrupopesoActual() {
        return this.animalGrupopesoActual;
    }
    
    public void setAnimalGrupopesoActual(Integer animalGrupopesoActual) {
        this.animalGrupopesoActual = animalGrupopesoActual;
    }

    
    @Column(name="ANIMAL_PESO_ACTUAL", precision=12, scale=0)
    public Float getAnimalPesoActual() {
        return this.animalPesoActual;
    }
    
    public void setAnimalPesoActual(Float animalPesoActual) {
        this.animalPesoActual = animalPesoActual;
    }

    
    @Column(name="ANIMAL_DIIO_ACTUAL")
    public Integer getAnimalDiioActual() {
        return this.animalDiioActual;
    }
    
    public void setAnimalDiioActual(Integer animalDiioActual) {
        this.animalDiioActual = animalDiioActual;
    }

    
    @Column(name="ANIMAL_CASTRADO")
    public Integer getAnimalCastrado() {
        return this.animalCastrado;
    }
    
    public void setAnimalCastrado(Integer animalCastrado) {
        this.animalCastrado = animalCastrado;
    }




}


