package edm;
// Generated 11-feb-2016 0:18:43 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name="CATEGORIA"
    ,catalog="CLARITYCOW"
)
public class Categoria  implements java.io.Serializable {


     private int categoriaId;
     private Integer categoriavalorId;
     private String categoriaDs;
     private Integer categoriaKgs;
     private Integer categoriaStatus;

    public Categoria() {
    }

	
    public Categoria(int categoriaId) {
        this.categoriaId = categoriaId;
    }
    public Categoria(int categoriaId, Integer categoriavalorId, String categoriaDs, Integer categoriaKgs, Integer categoriaStatus) {
       this.categoriaId = categoriaId;
       this.categoriavalorId = categoriavalorId;
       this.categoriaDs = categoriaDs;
       this.categoriaKgs = categoriaKgs;
       this.categoriaStatus = categoriaStatus;
    }
   
     @Id 

    
    @Column(name="CATEGORIA_ID", unique=true, nullable=false)
    public int getCategoriaId() {
        return this.categoriaId;
    }
    
    public void setCategoriaId(int categoriaId) {
        this.categoriaId = categoriaId;
    }

    
    @Column(name="CATEGORIAVALOR_ID")
    public Integer getCategoriavalorId() {
        return this.categoriavalorId;
    }
    
    public void setCategoriavalorId(Integer categoriavalorId) {
        this.categoriavalorId = categoriavalorId;
    }

    
    @Column(name="CATEGORIA_DS", length=50)
    public String getCategoriaDs() {
        return this.categoriaDs;
    }
    
    public void setCategoriaDs(String categoriaDs) {
        this.categoriaDs = categoriaDs;
    }

    
    @Column(name="CATEGORIA_KGS")
    public Integer getCategoriaKgs() {
        return this.categoriaKgs;
    }
    
    public void setCategoriaKgs(Integer categoriaKgs) {
        this.categoriaKgs = categoriaKgs;
    }

    
    @Column(name="CATEGORIA_STATUS")
    public Integer getCategoriaStatus() {
        return this.categoriaStatus;
    }
    
    public void setCategoriaStatus(Integer categoriaStatus) {
        this.categoriaStatus = categoriaStatus;
    }




}


