package edm;
// Generated 11-feb-2016 0:18:43 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Corral generated by hbm2java
 */
@Entity
@Table(name="CORRAL"
    ,catalog="CLARITYCOW"
)
public class Corral  implements java.io.Serializable {


     private int corralId;
     private Integer rupId;
     private String corralDs;
     private Integer corralStatus;

    public Corral() {
    }

	
    public Corral(int corralId, String corralDs) {
        this.corralId = corralId;
        this.corralDs = corralDs;
    }
    public Corral(int corralId, Integer rupId, String corralDs, Integer corralStatus) {
       this.corralId = corralId;
       this.rupId = rupId;
       this.corralDs = corralDs;
       this.corralStatus = corralStatus;
    }
   
     @Id 

    
    @Column(name="CORRAL_ID", unique=true, nullable=false)
    public int getCorralId() {
        return this.corralId;
    }
    
    public void setCorralId(int corralId) {
        this.corralId = corralId;
    }

    
    @Column(name="RUP_ID")
    public Integer getRupId() {
        return this.rupId;
    }
    
    public void setRupId(Integer rupId) {
        this.rupId = rupId;
    }

    
    @Column(name="CORRAL_DS", nullable=false, length=50)
    public String getCorralDs() {
        return this.corralDs;
    }
    
    public void setCorralDs(String corralDs) {
        this.corralDs = corralDs;
    }

    
    @Column(name="CORRAL_STATUS")
    public Integer getCorralStatus() {
        return this.corralStatus;
    }
    
    public void setCorralStatus(Integer corralStatus) {
        this.corralStatus = corralStatus;
    }




}


