package edm;
// Generated 11-feb-2016 0:18:43 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Diio generated by hbm2java
 */
@Entity
@Table(name="DIIO"
    ,catalog="CLARITYCOW"
)
public class Diio  implements java.io.Serializable {


     private int diioId;
     private Integer proveedorId;
     private Integer eventoId;
     private Integer diioEstado;
     private Date diioFechaCompra;
     private Date diioFechaIngreso;

    public Diio() {
    }

	
    public Diio(int diioId) {
        this.diioId = diioId;
    }
    public Diio(int diioId, Integer proveedorId, Integer eventoId, Integer diioEstado, Date diioFechaCompra, Date diioFechaIngreso) {
       this.diioId = diioId;
       this.proveedorId = proveedorId;
       this.eventoId = eventoId;
       this.diioEstado = diioEstado;
       this.diioFechaCompra = diioFechaCompra;
       this.diioFechaIngreso = diioFechaIngreso;
    }
   
     @Id 

    
    @Column(name="DIIO_ID", unique=true, nullable=false)
    public int getDiioId() {
        return this.diioId;
    }
    
    public void setDiioId(int diioId) {
        this.diioId = diioId;
    }

    
    @Column(name="PROVEEDOR_ID")
    public Integer getProveedorId() {
        return this.proveedorId;
    }
    
    public void setProveedorId(Integer proveedorId) {
        this.proveedorId = proveedorId;
    }

    
    @Column(name="EVENTO_ID")
    public Integer getEventoId() {
        return this.eventoId;
    }
    
    public void setEventoId(Integer eventoId) {
        this.eventoId = eventoId;
    }

    
    @Column(name="DIIO_ESTADO")
    public Integer getDiioEstado() {
        return this.diioEstado;
    }
    
    public void setDiioEstado(Integer diioEstado) {
        this.diioEstado = diioEstado;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DIIO_FECHA_COMPRA", length=10)
    public Date getDiioFechaCompra() {
        return this.diioFechaCompra;
    }
    
    public void setDiioFechaCompra(Date diioFechaCompra) {
        this.diioFechaCompra = diioFechaCompra;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DIIO_FECHA_INGRESO", length=10)
    public Date getDiioFechaIngreso() {
        return this.diioFechaIngreso;
    }
    
    public void setDiioFechaIngreso(Date diioFechaIngreso) {
        this.diioFechaIngreso = diioFechaIngreso;
    }




}


