package edm;
// Generated 11-feb-2016 0:18:43 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EstadoAnimal generated by hbm2java
 */
@Entity
@Table(name="ESTADO_ANIMAL"
    ,catalog="CLARITYCOW"
)
public class EstadoAnimal  implements java.io.Serializable {


     private int estadoanimalId;
     private Integer tipoestadoId;
     private String estadoanimalDs;
     private Integer estadoanimalStatus;

    public EstadoAnimal() {
    }

	
    public EstadoAnimal(int estadoanimalId) {
        this.estadoanimalId = estadoanimalId;
    }
    public EstadoAnimal(int estadoanimalId, Integer tipoestadoId, String estadoanimalDs, Integer estadoanimalStatus) {
       this.estadoanimalId = estadoanimalId;
       this.tipoestadoId = tipoestadoId;
       this.estadoanimalDs = estadoanimalDs;
       this.estadoanimalStatus = estadoanimalStatus;
    }
   
     @Id 

    
    @Column(name="ESTADOANIMAL_ID", unique=true, nullable=false)
    public int getEstadoanimalId() {
        return this.estadoanimalId;
    }
    
    public void setEstadoanimalId(int estadoanimalId) {
        this.estadoanimalId = estadoanimalId;
    }

    
    @Column(name="TIPOESTADO_ID")
    public Integer getTipoestadoId() {
        return this.tipoestadoId;
    }
    
    public void setTipoestadoId(Integer tipoestadoId) {
        this.tipoestadoId = tipoestadoId;
    }

    
    @Column(name="ESTADOANIMAL_DS", length=25)
    public String getEstadoanimalDs() {
        return this.estadoanimalDs;
    }
    
    public void setEstadoanimalDs(String estadoanimalDs) {
        this.estadoanimalDs = estadoanimalDs;
    }

    
    @Column(name="ESTADOANIMAL_STATUS")
    public Integer getEstadoanimalStatus() {
        return this.estadoanimalStatus;
    }
    
    public void setEstadoanimalStatus(Integer estadoanimalStatus) {
        this.estadoanimalStatus = estadoanimalStatus;
    }




}


