package edm;
// Generated 11-feb-2016 0:18:43 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Eventotipo generated by hbm2java
 */
@Entity
@Table(name="EVENTOTIPO"
    ,catalog="CLARITYCOW"
)
public class Eventotipo  implements java.io.Serializable {


     private int eventotipoId;
     private String eventotipoDs;
     private Integer eventotipoStatus;

    public Eventotipo() {
    }

	
    public Eventotipo(int eventotipoId) {
        this.eventotipoId = eventotipoId;
    }
    public Eventotipo(int eventotipoId, String eventotipoDs, Integer eventotipoStatus) {
       this.eventotipoId = eventotipoId;
       this.eventotipoDs = eventotipoDs;
       this.eventotipoStatus = eventotipoStatus;
    }
   
     @Id 

    
    @Column(name="EVENTOTIPO_ID", unique=true, nullable=false)
    public int getEventotipoId() {
        return this.eventotipoId;
    }
    
    public void setEventotipoId(int eventotipoId) {
        this.eventotipoId = eventotipoId;
    }

    
    @Column(name="EVENTOTIPO_DS", length=25)
    public String getEventotipoDs() {
        return this.eventotipoDs;
    }
    
    public void setEventotipoDs(String eventotipoDs) {
        this.eventotipoDs = eventotipoDs;
    }

    
    @Column(name="EVENTOTIPO_STATUS")
    public Integer getEventotipoStatus() {
        return this.eventotipoStatus;
    }
    
    public void setEventotipoStatus(Integer eventotipoStatus) {
        this.eventotipoStatus = eventotipoStatus;
    }




}


