package edm;
// Generated 11-feb-2016 0:18:43 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EventoTransporte generated by hbm2java
 */
@Entity
@Table(name="EVENTO_TRANSPORTE"
    ,catalog="CLARITYCOW"
)
public class EventoTransporte  implements java.io.Serializable {


     private int eventotransporteId;
     private Integer transporteId;
     private Integer eventoId;

    public EventoTransporte() {
    }

	
    public EventoTransporte(int eventotransporteId) {
        this.eventotransporteId = eventotransporteId;
    }
    public EventoTransporte(int eventotransporteId, Integer transporteId, Integer eventoId) {
       this.eventotransporteId = eventotransporteId;
       this.transporteId = transporteId;
       this.eventoId = eventoId;
    }
   
     @Id 

    
    @Column(name="EVENTOTRANSPORTE_ID", unique=true, nullable=false)
    public int getEventotransporteId() {
        return this.eventotransporteId;
    }
    
    public void setEventotransporteId(int eventotransporteId) {
        this.eventotransporteId = eventotransporteId;
    }

    
    @Column(name="TRANSPORTE_ID")
    public Integer getTransporteId() {
        return this.transporteId;
    }
    
    public void setTransporteId(Integer transporteId) {
        this.transporteId = transporteId;
    }

    
    @Column(name="EVENTO_ID")
    public Integer getEventoId() {
        return this.eventoId;
    }
    
    public void setEventoId(Integer eventoId) {
        this.eventoId = eventoId;
    }




}


