package edm;
// Generated 11-feb-2016 0:18:43 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EventoVenta generated by hbm2java
 */
@Entity
@Table(name="EVENTO_VENTA"
    ,catalog="CLARITYCOW"
)
public class EventoVenta  implements java.io.Serializable {


     private int eventoventaId;
     private Integer ventaId;
     private Integer eventoId;
     private Integer eventoventaValorNeto;
     private Integer eventoventaCategSag;
     private Float eventoventaPesoCanal;
     private Float eventoventaRendimiento;

    public EventoVenta() {
    }

	
    public EventoVenta(int eventoventaId) {
        this.eventoventaId = eventoventaId;
    }
    public EventoVenta(int eventoventaId, Integer ventaId, Integer eventoId, Integer eventoventaValorNeto, Integer eventoventaCategSag, Float eventoventaPesoCanal, Float eventoventaRendimiento) {
       this.eventoventaId = eventoventaId;
       this.ventaId = ventaId;
       this.eventoId = eventoId;
       this.eventoventaValorNeto = eventoventaValorNeto;
       this.eventoventaCategSag = eventoventaCategSag;
       this.eventoventaPesoCanal = eventoventaPesoCanal;
       this.eventoventaRendimiento = eventoventaRendimiento;
    }
   
     @Id 

    
    @Column(name="EVENTOVENTA_ID", unique=true, nullable=false)
    public int getEventoventaId() {
        return this.eventoventaId;
    }
    
    public void setEventoventaId(int eventoventaId) {
        this.eventoventaId = eventoventaId;
    }

    
    @Column(name="VENTA_ID")
    public Integer getVentaId() {
        return this.ventaId;
    }
    
    public void setVentaId(Integer ventaId) {
        this.ventaId = ventaId;
    }

    
    @Column(name="EVENTO_ID")
    public Integer getEventoId() {
        return this.eventoId;
    }
    
    public void setEventoId(Integer eventoId) {
        this.eventoId = eventoId;
    }

    
    @Column(name="EVENTOVENTA_VALOR_NETO")
    public Integer getEventoventaValorNeto() {
        return this.eventoventaValorNeto;
    }
    
    public void setEventoventaValorNeto(Integer eventoventaValorNeto) {
        this.eventoventaValorNeto = eventoventaValorNeto;
    }

    
    @Column(name="EVENTOVENTA_CATEG_SAG")
    public Integer getEventoventaCategSag() {
        return this.eventoventaCategSag;
    }
    
    public void setEventoventaCategSag(Integer eventoventaCategSag) {
        this.eventoventaCategSag = eventoventaCategSag;
    }

    
    @Column(name="EVENTOVENTA_PESO_CANAL", precision=12, scale=0)
    public Float getEventoventaPesoCanal() {
        return this.eventoventaPesoCanal;
    }
    
    public void setEventoventaPesoCanal(Float eventoventaPesoCanal) {
        this.eventoventaPesoCanal = eventoventaPesoCanal;
    }

    
    @Column(name="EVENTOVENTA_RENDIMIENTO", precision=12, scale=0)
    public Float getEventoventaRendimiento() {
        return this.eventoventaRendimiento;
    }
    
    public void setEventoventaRendimiento(Float eventoventaRendimiento) {
        this.eventoventaRendimiento = eventoventaRendimiento;
    }




}


