package edm;
// Generated 11-feb-2016 0:18:43 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ingrediente generated by hbm2java
 */
@Entity
@Table(name="INGREDIENTE"
    ,catalog="CLARITYCOW"
)
public class Ingrediente  implements java.io.Serializable {


     private int ingredienteId;
     private String ingredienteDs;
     private Integer ingredienteStatus;

    public Ingrediente() {
    }

	
    public Ingrediente(int ingredienteId) {
        this.ingredienteId = ingredienteId;
    }
    public Ingrediente(int ingredienteId, String ingredienteDs, Integer ingredienteStatus) {
       this.ingredienteId = ingredienteId;
       this.ingredienteDs = ingredienteDs;
       this.ingredienteStatus = ingredienteStatus;
    }
   
     @Id 

    
    @Column(name="INGREDIENTE_ID", unique=true, nullable=false)
    public int getIngredienteId() {
        return this.ingredienteId;
    }
    
    public void setIngredienteId(int ingredienteId) {
        this.ingredienteId = ingredienteId;
    }

    
    @Column(name="INGREDIENTE_DS", length=25)
    public String getIngredienteDs() {
        return this.ingredienteDs;
    }
    
    public void setIngredienteDs(String ingredienteDs) {
        this.ingredienteDs = ingredienteDs;
    }

    
    @Column(name="INGREDIENTE_STATUS")
    public Integer getIngredienteStatus() {
        return this.ingredienteStatus;
    }
    
    public void setIngredienteStatus(Integer ingredienteStatus) {
        this.ingredienteStatus = ingredienteStatus;
    }




}


