package edm;
// Generated 11-feb-2016 0:18:43 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * InsumoTipo generated by hbm2java
 */
@Entity
@Table(name="INSUMO_TIPO"
    ,catalog="CLARITYCOW"
)
public class InsumoTipo  implements java.io.Serializable {


     private int insumotipoId;
     private String insumotipoDs;
     private Integer insumotipoStatus;

    public InsumoTipo() {
    }

	
    public InsumoTipo(int insumotipoId) {
        this.insumotipoId = insumotipoId;
    }
    public InsumoTipo(int insumotipoId, String insumotipoDs, Integer insumotipoStatus) {
       this.insumotipoId = insumotipoId;
       this.insumotipoDs = insumotipoDs;
       this.insumotipoStatus = insumotipoStatus;
    }
   
     @Id 

    
    @Column(name="INSUMOTIPO_ID", unique=true, nullable=false)
    public int getInsumotipoId() {
        return this.insumotipoId;
    }
    
    public void setInsumotipoId(int insumotipoId) {
        this.insumotipoId = insumotipoId;
    }

    
    @Column(name="INSUMOTIPO_DS", length=50)
    public String getInsumotipoDs() {
        return this.insumotipoDs;
    }
    
    public void setInsumotipoDs(String insumotipoDs) {
        this.insumotipoDs = insumotipoDs;
    }

    
    @Column(name="INSUMOTIPO_STATUS")
    public Integer getInsumotipoStatus() {
        return this.insumotipoStatus;
    }
    
    public void setInsumotipoStatus(Integer insumotipoStatus) {
        this.insumotipoStatus = insumotipoStatus;
    }




}


