package edm;
// Generated 11-feb-2016 0:18:43 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RupTipo generated by hbm2java
 */
@Entity
@Table(name="RUP_TIPO"
    ,catalog="CLARITYCOW"
)
public class RupTipo  implements java.io.Serializable {


     private int ruptipoId;
     private String ruptipoDs;
     private Integer ruptipoStatus;

    public RupTipo() {
    }

	
    public RupTipo(int ruptipoId) {
        this.ruptipoId = ruptipoId;
    }
    public RupTipo(int ruptipoId, String ruptipoDs, Integer ruptipoStatus) {
       this.ruptipoId = ruptipoId;
       this.ruptipoDs = ruptipoDs;
       this.ruptipoStatus = ruptipoStatus;
    }
   
     @Id 

    
    @Column(name="RUPTIPO_ID", unique=true, nullable=false)
    public int getRuptipoId() {
        return this.ruptipoId;
    }
    
    public void setRuptipoId(int ruptipoId) {
        this.ruptipoId = ruptipoId;
    }

    
    @Column(name="RUPTIPO_DS", length=25)
    public String getRuptipoDs() {
        return this.ruptipoDs;
    }
    
    public void setRuptipoDs(String ruptipoDs) {
        this.ruptipoDs = ruptipoDs;
    }

    
    @Column(name="RUPTIPO_STATUS")
    public Integer getRuptipoStatus() {
        return this.ruptipoStatus;
    }
    
    public void setRuptipoStatus(Integer ruptipoStatus) {
        this.ruptipoStatus = ruptipoStatus;
    }




}


