package edm;
// Generated 11-feb-2016 0:18:43 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sexo generated by hbm2java
 */
@Entity
@Table(name="SEXO"
    ,catalog="CLARITYCOW"
)
public class Sexo  implements java.io.Serializable {


     private int sexoId;
     private String sexoDs;
     private Integer sexoStatus;

    public Sexo() {
    }

	
    public Sexo(int sexoId) {
        this.sexoId = sexoId;
    }
    public Sexo(int sexoId, String sexoDs, Integer sexoStatus) {
       this.sexoId = sexoId;
       this.sexoDs = sexoDs;
       this.sexoStatus = sexoStatus;
    }
   
     @Id 

    
    @Column(name="SEXO_ID", unique=true, nullable=false)
    public int getSexoId() {
        return this.sexoId;
    }
    
    public void setSexoId(int sexoId) {
        this.sexoId = sexoId;
    }

    
    @Column(name="SEXO_DS", length=25)
    public String getSexoDs() {
        return this.sexoDs;
    }
    
    public void setSexoDs(String sexoDs) {
        this.sexoDs = sexoDs;
    }

    
    @Column(name="SEXO_STATUS")
    public Integer getSexoStatus() {
        return this.sexoStatus;
    }
    
    public void setSexoStatus(Integer sexoStatus) {
        this.sexoStatus = sexoStatus;
    }




}


