package edm;
// Generated 11-feb-2016 0:18:43 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoEstado generated by hbm2java
 */
@Entity
@Table(name="TIPO_ESTADO"
    ,catalog="CLARITYCOW"
)
public class TipoEstado  implements java.io.Serializable {


     private int tipoestadoId;
     private String tipoestadoDs;
     private Integer tipoestadoStatus;

    public TipoEstado() {
    }

	
    public TipoEstado(int tipoestadoId) {
        this.tipoestadoId = tipoestadoId;
    }
    public TipoEstado(int tipoestadoId, String tipoestadoDs, Integer tipoestadoStatus) {
       this.tipoestadoId = tipoestadoId;
       this.tipoestadoDs = tipoestadoDs;
       this.tipoestadoStatus = tipoestadoStatus;
    }
   
     @Id 

    
    @Column(name="TIPOESTADO_ID", unique=true, nullable=false)
    public int getTipoestadoId() {
        return this.tipoestadoId;
    }
    
    public void setTipoestadoId(int tipoestadoId) {
        this.tipoestadoId = tipoestadoId;
    }

    
    @Column(name="TIPOESTADO_DS", length=25)
    public String getTipoestadoDs() {
        return this.tipoestadoDs;
    }
    
    public void setTipoestadoDs(String tipoestadoDs) {
        this.tipoestadoDs = tipoestadoDs;
    }

    
    @Column(name="TIPOESTADO_STATUS")
    public Integer getTipoestadoStatus() {
        return this.tipoestadoStatus;
    }
    
    public void setTipoestadoStatus(Integer tipoestadoStatus) {
        this.tipoestadoStatus = tipoestadoStatus;
    }




}


