package edm;
// Generated 11-feb-2016 0:18:43 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Transportista generated by hbm2java
 */
@Entity
@Table(name="TRANSPORTISTA"
    ,catalog="CLARITYCOW"
)
public class Transportista  implements java.io.Serializable {


     private int transportistaId;
     private int transportistaNrut;
     private String transportistaDrut;
     private String transportistaNombre;
     private Integer transportistaStatus;

    public Transportista() {
    }

	
    public Transportista(int transportistaId, int transportistaNrut) {
        this.transportistaId = transportistaId;
        this.transportistaNrut = transportistaNrut;
    }
    public Transportista(int transportistaId, int transportistaNrut, String transportistaDrut, String transportistaNombre, Integer transportistaStatus) {
       this.transportistaId = transportistaId;
       this.transportistaNrut = transportistaNrut;
       this.transportistaDrut = transportistaDrut;
       this.transportistaNombre = transportistaNombre;
       this.transportistaStatus = transportistaStatus;
    }
   
     @Id 

    
    @Column(name="TRANSPORTISTA_ID", unique=true, nullable=false)
    public int getTransportistaId() {
        return this.transportistaId;
    }
    
    public void setTransportistaId(int transportistaId) {
        this.transportistaId = transportistaId;
    }

    
    @Column(name="TRANSPORTISTA_NRUT", nullable=false)
    public int getTransportistaNrut() {
        return this.transportistaNrut;
    }
    
    public void setTransportistaNrut(int transportistaNrut) {
        this.transportistaNrut = transportistaNrut;
    }

    
    @Column(name="TRANSPORTISTA_DRUT", length=1)
    public String getTransportistaDrut() {
        return this.transportistaDrut;
    }
    
    public void setTransportistaDrut(String transportistaDrut) {
        this.transportistaDrut = transportistaDrut;
    }

    
    @Column(name="TRANSPORTISTA_NOMBRE", length=50)
    public String getTransportistaNombre() {
        return this.transportistaNombre;
    }
    
    public void setTransportistaNombre(String transportistaNombre) {
        this.transportistaNombre = transportistaNombre;
    }

    
    @Column(name="TRANSPORTISTA_STATUS")
    public Integer getTransportistaStatus() {
        return this.transportistaStatus;
    }
    
    public void setTransportistaStatus(Integer transportistaStatus) {
        this.transportistaStatus = transportistaStatus;
    }




}


