package edm;
// Generated 11-feb-2016 0:18:43 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Vehiculo generated by hbm2java
 */
@Entity
@Table(name="VEHICULO"
    ,catalog="CLARITYCOW"
)
public class Vehiculo  implements java.io.Serializable {


     private int vehiculoId;
     private int tipovehiculoId;
     private String vehiculoPatente;
     private Integer vehiculoStatus;

    public Vehiculo() {
    }

	
    public Vehiculo(int vehiculoId, int tipovehiculoId, String vehiculoPatente) {
        this.vehiculoId = vehiculoId;
        this.tipovehiculoId = tipovehiculoId;
        this.vehiculoPatente = vehiculoPatente;
    }
    public Vehiculo(int vehiculoId, int tipovehiculoId, String vehiculoPatente, Integer vehiculoStatus) {
       this.vehiculoId = vehiculoId;
       this.tipovehiculoId = tipovehiculoId;
       this.vehiculoPatente = vehiculoPatente;
       this.vehiculoStatus = vehiculoStatus;
    }
   
     @Id 

    
    @Column(name="VEHICULO_ID", unique=true, nullable=false)
    public int getVehiculoId() {
        return this.vehiculoId;
    }
    
    public void setVehiculoId(int vehiculoId) {
        this.vehiculoId = vehiculoId;
    }

    
    @Column(name="TIPOVEHICULO_ID", nullable=false)
    public int getTipovehiculoId() {
        return this.tipovehiculoId;
    }
    
    public void setTipovehiculoId(int tipovehiculoId) {
        this.tipovehiculoId = tipovehiculoId;
    }

    
    @Column(name="VEHICULO_PATENTE", nullable=false, length=10)
    public String getVehiculoPatente() {
        return this.vehiculoPatente;
    }
    
    public void setVehiculoPatente(String vehiculoPatente) {
        this.vehiculoPatente = vehiculoPatente;
    }

    
    @Column(name="VEHICULO_STATUS")
    public Integer getVehiculoStatus() {
        return this.vehiculoStatus;
    }
    
    public void setVehiculoStatus(Integer vehiculoStatus) {
        this.vehiculoStatus = vehiculoStatus;
    }




}


