package edm;
// Generated 11-feb-2016 0:18:43 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * VehiculoTipo generated by hbm2java
 */
@Entity
@Table(name="VEHICULO_TIPO"
    ,catalog="CLARITYCOW"
)
public class VehiculoTipo  implements java.io.Serializable {


     private int vehiculotipoId;
     private String vehiculotipoDs;
     private Integer vehiculotipoStatus;

    public VehiculoTipo() {
    }

	
    public VehiculoTipo(int vehiculotipoId, String vehiculotipoDs) {
        this.vehiculotipoId = vehiculotipoId;
        this.vehiculotipoDs = vehiculotipoDs;
    }
    public VehiculoTipo(int vehiculotipoId, String vehiculotipoDs, Integer vehiculotipoStatus) {
       this.vehiculotipoId = vehiculotipoId;
       this.vehiculotipoDs = vehiculotipoDs;
       this.vehiculotipoStatus = vehiculotipoStatus;
    }
   
     @Id 

    
    @Column(name="VEHICULOTIPO_ID", unique=true, nullable=false)
    public int getVehiculotipoId() {
        return this.vehiculotipoId;
    }
    
    public void setVehiculotipoId(int vehiculotipoId) {
        this.vehiculotipoId = vehiculotipoId;
    }

    
    @Column(name="VEHICULOTIPO_DS", nullable=false, length=25)
    public String getVehiculotipoDs() {
        return this.vehiculotipoDs;
    }
    
    public void setVehiculotipoDs(String vehiculotipoDs) {
        this.vehiculotipoDs = vehiculotipoDs;
    }

    
    @Column(name="VEHICULOTIPO_STATUS")
    public Integer getVehiculotipoStatus() {
        return this.vehiculotipoStatus;
    }
    
    public void setVehiculotipoStatus(Integer vehiculotipoStatus) {
        this.vehiculotipoStatus = vehiculotipoStatus;
    }




}


