package edm;
// Generated 11-feb-2016 0:18:43 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Venta generated by hbm2java
 */
@Entity
@Table(name="VENTA"
    ,catalog="CLARITYCOW"
)
public class Venta  implements java.io.Serializable {


     private int ventaId;
     private Integer transporteId;
     private Integer clienteId;
     private Date ventaFecha;
     private Integer ventaFactura;
     private Integer ventaValorFlete;
     private Integer ventaComision;
     private Integer ventaExamenes;
     private Integer ventaPrecioNeto;

    public Venta() {
    }

	
    public Venta(int ventaId, Date ventaFecha) {
        this.ventaId = ventaId;
        this.ventaFecha = ventaFecha;
    }
    public Venta(int ventaId, Integer transporteId, Integer clienteId, Date ventaFecha, Integer ventaFactura, Integer ventaValorFlete, Integer ventaComision, Integer ventaExamenes, Integer ventaPrecioNeto) {
       this.ventaId = ventaId;
       this.transporteId = transporteId;
       this.clienteId = clienteId;
       this.ventaFecha = ventaFecha;
       this.ventaFactura = ventaFactura;
       this.ventaValorFlete = ventaValorFlete;
       this.ventaComision = ventaComision;
       this.ventaExamenes = ventaExamenes;
       this.ventaPrecioNeto = ventaPrecioNeto;
    }
   
     @Id 

    
    @Column(name="VENTA_ID", unique=true, nullable=false)
    public int getVentaId() {
        return this.ventaId;
    }
    
    public void setVentaId(int ventaId) {
        this.ventaId = ventaId;
    }

    
    @Column(name="TRANSPORTE_ID")
    public Integer getTransporteId() {
        return this.transporteId;
    }
    
    public void setTransporteId(Integer transporteId) {
        this.transporteId = transporteId;
    }

    
    @Column(name="CLIENTE_ID")
    public Integer getClienteId() {
        return this.clienteId;
    }
    
    public void setClienteId(Integer clienteId) {
        this.clienteId = clienteId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="VENTA_FECHA", nullable=false, length=10)
    public Date getVentaFecha() {
        return this.ventaFecha;
    }
    
    public void setVentaFecha(Date ventaFecha) {
        this.ventaFecha = ventaFecha;
    }

    
    @Column(name="VENTA_FACTURA")
    public Integer getVentaFactura() {
        return this.ventaFactura;
    }
    
    public void setVentaFactura(Integer ventaFactura) {
        this.ventaFactura = ventaFactura;
    }

    
    @Column(name="VENTA_VALOR_FLETE")
    public Integer getVentaValorFlete() {
        return this.ventaValorFlete;
    }
    
    public void setVentaValorFlete(Integer ventaValorFlete) {
        this.ventaValorFlete = ventaValorFlete;
    }

    
    @Column(name="VENTA_COMISION")
    public Integer getVentaComision() {
        return this.ventaComision;
    }
    
    public void setVentaComision(Integer ventaComision) {
        this.ventaComision = ventaComision;
    }

    
    @Column(name="VENTA_EXAMENES")
    public Integer getVentaExamenes() {
        return this.ventaExamenes;
    }
    
    public void setVentaExamenes(Integer ventaExamenes) {
        this.ventaExamenes = ventaExamenes;
    }

    
    @Column(name="VENTA_PRECIO_NETO")
    public Integer getVentaPrecioNeto() {
        return this.ventaPrecioNeto;
    }
    
    public void setVentaPrecioNeto(Integer ventaPrecioNeto) {
        this.ventaPrecioNeto = ventaPrecioNeto;
    }




}


